Feature: Feature1

A short summary of the feature

@tag1 
Scenario: scenario
	Given Navigate to url
	When click on about link
	Then about link page should open 


	Scenario: scenario1
	Given Navigate to url
	When click on contact link
	Then contact link should open

@tag2 
Scenario: scenario2
	Given Navigate to url
	When click on joinemaillink
	Then joinemaillink should open

@tag3 
Scenario: scenario3
	Given Navigate to url
	When click on softwareblog
	Then softwareblog will open

@tag4
Scenario: scenario4
	Given Navigate to url
	When click on marketblog
	Then marketblog should open


	

